language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - postgresql

env:
  global:
    - SYMFONY__POSTGRESQL_HOST="127.0.0.1"
    - SYMFONY__POSTGRESQL_USER="postgres"
    - SYMFONY__POSTGRESQL_PASSWORD=""
    - SYMFONY__POSTGRESQL_DBNAME="travis_ci_test"

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: SYMFONY_VERSION=2.8.*
        - php: 7.0
          env: SYMFONY_VERSION=3.0.*
        - php: 7.0

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - psql -c 'create database travis_ci_test;' -U postgres

install:
    - composer update --no-interaction --prefer-dist

script:
    - phpunit
